/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pengelolaankrsForm;

import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import koneksidb.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author User
 */
public class inputKRS extends javax.swing.JFrame {
    
    private koneksi obj;
    private DefaultTableModel tableModel;


    /**
     * Creates new form mhsForm
     */
    public inputKRS() {
       initComponents();
        this.setLocationRelativeTo(null);
        
        obj = new koneksi();
        tableModel = new DefaultTableModel();
        tableKrs.setModel(tableModel);
        tableModel.addColumn("Id Matkul");
        tableModel.addColumn("Mata Kuliah");
        tableModel.addColumn("SKS");
        tableModel.addColumn("Kelas");
        tableModel.addColumn("Jurusan");
        tableModel.addColumn("Semester");
        tableModel.addColumn("Dosen");
        
        tampilDataKrs();
    }
        
        public void tampilDataKrs() {
         try {
            tableModel.setRowCount(0);

            String query = "SELECT * FROM krs ";
            try (PreparedStatement preparedStatement = (PreparedStatement) obj.konek.prepareStatement(query);
                 ResultSet data = preparedStatement.executeQuery()) {
                while (data.next()) {
                    Object[] line = new Object[7];
                    line[0] = data.getString("id_matkul");
                    line[1] = data.getString("mata_kuliah");
                    line[2] = data.getString("sks");
                    line[3] = data.getString("kelas");
                    line[4] = data.getString("jurusan");
                    line[5] = data.getString("semester");
                    line[6] = data.getString("dosen");
                    tableModel.addRow(line);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kelasCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        matkulTF = new javax.swing.JTextField();
        sksCB = new javax.swing.JComboBox<>();
        jurusanCB = new javax.swing.JComboBox<>();
        semCB = new javax.swing.JComboBox<>();
        dosenTF = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKrs = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("INPUT KRS");

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Pastikan Data Anda Terdaftar Sebelum Input KRS");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("BUKA DATA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel5.setText("ID MATKUL");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel6.setText("MATA KULIAH");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel7.setText("SKS");

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel8.setText("SEMESTER");

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel9.setText("DOSEN");

        jLabel3.setText("KELAS");

        kelasCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Reguler", "Non Reguler", " " }));

        jLabel4.setText("JURUSAN");

        sksCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "1", "2", "3", "4" }));
        sksCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sksCBActionPerformed(evt);
            }
        });

        jurusanCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- -", "Teknik Informatika", "Sistem Informasi", "Teknik Sipil", "Teknik Industri", "Budidaya Perairan", "Desain Komunikasi Visual", "Desain Produk", "Teknik Elektro" }));
        jurusanCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanCBActionPerformed(evt);
            }
        });

        semCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "1", "2", "3", "4", "5", "6", "7", "8" }));

        dosenTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosenTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jurusanCB, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dosenTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(semCB, javax.swing.GroupLayout.Alignment.LEADING, 0, 140, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sksCB, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idTF, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addComponent(matkulTF, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addComponent(kelasCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matkulTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sksCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jurusanCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(semCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dosenTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setText("TAMBAH");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableKrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tableKrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKrsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKrs);

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("CETAK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(294, 294, 294))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnClear)
                                        .addGap(51, 51, 51)
                                        .addComponent(btnKeluar)
                                        .addGap(89, 89, 89))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnSimpan)
                                .addGap(37, 37, 37)
                                .addComponent(btnUbah)
                                .addGap(39, 39, 39)
                                .addComponent(btnHapus)))
                        .addGap(8, 8, 8)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(290, 290, 290))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKeluar)
                            .addComponent(btnClear))
                        .addGap(21, 21, 21))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            if (matkulTF.getText().isEmpty() ||
                sksCB.getSelectedItem() == null || kelasCB.getSelectedItem() == null ||
                jurusanCB.getSelectedItem() == null || semCB.getSelectedItem() == null || dosenTF.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Silahkan isi semua data terlebih dahulu!");
            } else {
                // Cek apakah data dengan nilai yang akan dihapus sudah ada
                String sqlCheck = "SELECT * FROM krs WHERE " +
                                   "mata_kuliah=? AND sks=? AND kelas=? AND jurusan=? AND semester=? AND dosen=?";
                PreparedStatement checkStmt = (PreparedStatement) obj.konek.prepareStatement(sqlCheck);

                checkStmt.setString(1, matkulTF.getText());
                checkStmt.setString(2, (String) sksCB.getSelectedItem());
                checkStmt.setString(3, (String) kelasCB.getSelectedItem());
                checkStmt.setString(4, (String) jurusanCB.getSelectedItem());
                checkStmt.setString(5, (String) semCB.getSelectedItem());
                checkStmt.setString(6, dosenTF.getText());

                ResultSet resultSet = checkStmt.executeQuery();

                if (resultSet.next()) {
                    // Data ditemukan, minta konfirmasi sebelum menghapus
                    int confirmDelete = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

                    if (confirmDelete == JOptionPane.YES_OPTION) {
                        // Pengguna mengonfirmasi untuk menghapus, jalankan perintah DELETE
                        String sqlDelete = "DELETE FROM krs WHERE " +
                                           "mata_kuliah=? AND sks=? AND kelas=? AND jurusan=? AND semester=? AND dosen=?";
                        PreparedStatement deleteStmt = (PreparedStatement) obj.konek.prepareStatement(sqlDelete);

                        deleteStmt.setString(1, matkulTF.getText());
                        deleteStmt.setString(2, (String) sksCB.getSelectedItem());
                        deleteStmt.setString(3, (String) kelasCB.getSelectedItem());
                        deleteStmt.setString(4, (String) jurusanCB.getSelectedItem());
                        deleteStmt.setString(5, (String) semCB.getSelectedItem());
                        deleteStmt.setString(6, dosenTF.getText());

                        // Eksekusi query DELETE
                        int hasilDelete = deleteStmt.executeUpdate();

                        if (hasilDelete > 0) {
                            tampilDataKrs();
                            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                        }
                    }
                } else {
                    // Data tidak ditemukan
                    JOptionPane.showMessageDialog(this, "Data dengan nilai tersebut tidak ditemukan!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          String path = ".\\src\\report\\reportDataKrs.jasper";
        try {
        // Mengatur koneksi database (gantilah parameter koneksi dengan yang sesuai)
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/aplikasi_krs", "root", "");

        // Mengisi laporan dengan data dari database
        JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);

        // Menampilkan laporan menggunakan JasperViewer
        JasperViewer jviewer = new JasperViewer(jprint, false);
        jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jviewer.setVisible(true);

        // Menutup koneksi database setelah selesai
        conn.close();
     } catch (JRException | SQLException e) {
        // Menangkap dan menampilkan exception
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new mhsForm().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
    if (idTF.getText().isEmpty() || matkulTF.getText().isEmpty() ||
        sksCB.getSelectedItem() == null || kelasCB.getSelectedItem() == null ||
        jurusanCB.getSelectedItem() == null || semCB.getSelectedItem() == null || dosenTF.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Silahkan isi semua data terlebih dahulu!");
    } else {
        // Cek apakah data dengan id_matkul yang sama sudah ada
        String sqlCheck = "SELECT * FROM krs WHERE id_matkul=?";
        PreparedStatement checkStmt = (PreparedStatement) obj.konek.prepareStatement(sqlCheck);
        checkStmt.setString(1, idTF.getText());
        ResultSet resultSet = checkStmt.executeQuery();

        if (resultSet.next()) {
            // Data sudah ada, tampilkan pesan kesalahan
            JOptionPane.showMessageDialog(this, "Data dengan ID Mata Kuliah tersebut sudah ada. Gunakan tombol Edit untuk mengubah data.");
        } else {
            // Data belum ada, jalankan perintah INSERT
            String sqlInsert = "INSERT INTO krs (id_matkul, mata_kuliah, sks, kelas, jurusan, semester, dosen) " +
                               "VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement insertStmt = (PreparedStatement) obj.konek.prepareStatement(sqlInsert);

            insertStmt.setString(1, idTF.getText());
            insertStmt.setString(2, matkulTF.getText());
            insertStmt.setString(3, (String) sksCB.getSelectedItem());
            insertStmt.setString(4, (String) kelasCB.getSelectedItem());
            insertStmt.setString(5, (String) jurusanCB.getSelectedItem());
            insertStmt.setString(6, (String) semCB.getSelectedItem());
            insertStmt.setString(7, dosenTF.getText());

            // Eksekusi query INSERT
            int hasilInsert = insertStmt.executeUpdate();

            if (hasilInsert > 0) {
                tampilDataKrs();
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan data.");
            }
        }
    }
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
     
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void sksCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sksCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sksCBActionPerformed

    private void jurusanCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jurusanCBActionPerformed

    private void dosenTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosenTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosenTFActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try {
            if (idTF.getText().isEmpty() || matkulTF.getText().isEmpty() ||
                sksCB.getSelectedItem() == null || kelasCB.getSelectedItem() == null ||
                jurusanCB.getSelectedItem() == null || semCB.getSelectedItem() == null || dosenTF.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Silahkan isi semua data terlebih dahulu!");
            } else {
                // Cek apakah data dengan id_matkul yang sama sudah ada
                String sqlCheck = "SELECT * FROM krs WHERE id_matkul=?";
                PreparedStatement checkStmt = (PreparedStatement) obj.konek.prepareStatement(sqlCheck);
                checkStmt.setString(1, idTF.getText());
                ResultSet resultSet = checkStmt.executeQuery();

                if (resultSet.next()) {
                    // Data sudah ada, jalankan perintah UPDATE
                    String sqlUpdate = "UPDATE krs SET mata_kuliah=?, sks=?, kelas=?, jurusan=?, " +
                                       "semester=?, dosen=? WHERE id_matkul=?";
                    PreparedStatement updateStmt = (PreparedStatement) obj.konek.prepareStatement(sqlUpdate);

                    updateStmt.setString(1, matkulTF.getText());
                    updateStmt.setString(2, (String) sksCB.getSelectedItem());
                    updateStmt.setString(3, (String) kelasCB.getSelectedItem());
                    updateStmt.setString(4, (String) jurusanCB.getSelectedItem());
                    updateStmt.setString(5, (String) semCB.getSelectedItem());
                    updateStmt.setString(6, dosenTF.getText());
                    updateStmt.setString(7, idTF.getText());

                    // Eksekusi query UPDATE
                    int hasilUpdate = updateStmt.executeUpdate();

                    if (hasilUpdate > 0) {
                        tampilDataKrs();
                        JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Gagal mengubah data. Pastikan ID Mata Kuliah yang dimasukkan benar.");
                    }
                } else {
                    // Data belum ada, tampilkan pesan kesalahan
                    JOptionPane.showMessageDialog(this, "Data dengan ID Mata Kuliah tersebut belum ada. Gunakan tombol Tambah untuk menambahkan data baru.");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnUbahActionPerformed

    private void tableKrsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKrsMouseClicked
        // TODO add your handling code here:
        int baris = tableKrs.getSelectedRow();
        if (baris != -1) {
            String id_matkul = tableKrs.getValueAt(baris, 0).toString();
            String mata_kuliah = tableKrs.getValueAt(baris, 1).toString();
            String sks = tableKrs.getValueAt(baris, 2).toString();
            String kelas = tableKrs.getValueAt(baris, 3).toString();
            String jurusan = tableKrs.getValueAt(baris, 4).toString();
            String semester = tableKrs.getValueAt(baris, 5).toString();
            String dosen = tableKrs.getValueAt(baris, 6).toString();

            idTF.setText(id_matkul);
            matkulTF.setText(mata_kuliah);

            // Pastikan item yang dipilih pada ComboBox sesuai dengan data yang diambil dari tabel
            sksCB.setSelectedItem(sks);
            kelasCB.setSelectedItem(kelas);
            jurusanCB.setSelectedItem(jurusan);
            semCB.setSelectedItem(semester);
            dosenTF.setText(dosen);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris terlebih dahulu.");
        }

    }//GEN-LAST:event_tableKrsMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        idTF.setText("");
        matkulTF.setText("");
        sksCB.setSelectedIndex(0);
        kelasCB.setSelectedIndex(0);
        jurusanCB.setSelectedIndex(0);
        semCB.setSelectedIndex(0);
        dosenTF.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputKRS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField dosenTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jurusanCB;
    private javax.swing.JComboBox<String> kelasCB;
    private javax.swing.JTextField matkulTF;
    private javax.swing.JComboBox<String> semCB;
    private javax.swing.JComboBox<String> sksCB;
    private javax.swing.JTable tableKrs;
    // End of variables declaration//GEN-END:variables


}